// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF96qL5Pt0obSC7bQfTmqRkkNHwmIu-fg',
    appId: '1:124299243590:web:da6f136488d0b588f75a47',
    messagingSenderId: '124299243590',
    projectId: 'snake-game-online-c268f',
    authDomain: 'snake-game-online-c268f.firebaseapp.com',
    storageBucket: 'snake-game-online-c268f.appspot.com',
    measurementId: 'G-KEB56P24L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9RjtmZARl3uZ1D1pNyiMNgca68ea6M3g',
    appId: '1:124299243590:android:b0ad6bbdf1199f50f75a47',
    messagingSenderId: '124299243590',
    projectId: 'snake-game-online-c268f',
    storageBucket: 'snake-game-online-c268f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChmKzuM01t9DjfsINI8BcxF8IWLEB2KiY',
    appId: '1:124299243590:ios:33c56846ade9e192f75a47',
    messagingSenderId: '124299243590',
    projectId: 'snake-game-online-c268f',
    storageBucket: 'snake-game-online-c268f.appspot.com',
    iosClientId: '124299243590-a6m794lsj3mc0tdq5h3lha26jh7li06m.apps.googleusercontent.com',
    iosBundleId: 'com.example.snakeGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChmKzuM01t9DjfsINI8BcxF8IWLEB2KiY',
    appId: '1:124299243590:ios:33c56846ade9e192f75a47',
    messagingSenderId: '124299243590',
    projectId: 'snake-game-online-c268f',
    storageBucket: 'snake-game-online-c268f.appspot.com',
    iosClientId: '124299243590-a6m794lsj3mc0tdq5h3lha26jh7li06m.apps.googleusercontent.com',
    iosBundleId: 'com.example.snakeGame',
  );
}
